spring:
   application:
      name: order-service
   data:
      mongodb:
         uri: mongodb://localhost:27017/test
server:
   port: 9003
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8099/eureka/
   instance:
      preferIpAddress: true
      hostName: 192.168.1.10